# Docker compose file for inv.nadeko.net

services:

  invidious-refresher:
    image: git.nadeko.net/fijxu/invidious:latest
    restart: unless-stopped
    volumes:
      - ./config/config-refresher.yml:/etc/invidious/config.yml:ro
      - ./logs:/var/log/invidious:rw
      - /var/run/postgresql/.s.PGSQL.5432:/var/run/postgresql/.s.PGSQL.5432:rw
      - /var/run/valkey/valkey.sock:/var/run/redis/redis.sock:rw
    environment:
      INVIDIOUS_CONFIG_FILE: /etc/invidious/config.yml

  invidious:
    image: git.nadeko.net/fijxu/invidious:latest
    restart: unless-stopped
    deploy: 
      replicas: 8
    volumes:
      - ./config/config.yml:/etc/invidious/config.yml:ro
      - ./logs:/var/log/invidious:rw
      - /var/run/postgresql/.s.PGSQL.5432:/var/run/postgresql/.s.PGSQL.5432:rw
      - /var/run/valkey/valkey.sock:/var/run/redis/redis.sock:rw
    environment:
      INVIDIOUS_CONFIG_FILE: /etc/invidious/config.yml

  invidious-nginx:
   image: nginx:latest
   restart: unless-stopped
   volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
   depends_on:
     - invidious
   ports:
     - "127.0.0.1:10011:3000"
