version: "3"
services:
  valkey:
    image: valkey/valkey:7.2-alpine
    restart: unless-stopped
    volumes:
      - "./valkey:/data"
    ports:
      - "127.0.0.1:6379:6379"
  invidious:
    build:
      context: .
      dockerfile: docker/Dockerfile
    # image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    restart: unless-stopped
    ports:
      - "100.64.0.6:3000:3000"
    environment:
      INVIDIOUS_CONFIG: |
        check_tables: true
        external_port: 443
        domain: iv.duti.dev
        https_only: true
        statistics_enabled: true
        hmac_key: "JKnsuih7876873!@#"
        redis_url: tcp://valkey:6379
        db:
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
          dbname: invidious
        invidious_companion:
         - private_url: "http://invidious_companion:8282"
           public_url: "https://iv.duti.dev/companion"
        invidious_companion_key: "IAmNotAHuTaoMainBro"

    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db
      - valkey
      - invidious_companion

  invidious_companion:
    build:
      context: ./external/invidious-companion
      dockerfile: Dockerfile
    image: quay.io/invidious/invidious-companion:latest
    ports:
      - 100.64.0.6:8282:8282
    environment:
      SERVER_SECRET_KEY: IAmNotAHuTaoMainBro
      SERVER_BASE_URL: https://iv.duti.dev/companion
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    user: 10001:10001
    # cache for youtube library
    # volumes:
    #   - /var/tmp/youtubei.js:/var/tmp/youtubei.js:rw
    security_opt:
      - no-new-privileges:true
 
  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  ptgen:
    build:
      context: ./external/youtube-po-token-generator
      dockerfile: Dockerfile
    cpus: 0.1
    restart: unless-stopped
    environment:
      - HOST=valkey
      - RENEW_INTERVAL=60
    depends_on:
      - haproxy

volumes:
  postgresdata: 

