# Warning: This docker-compose file is made for development purposes.
# Using it will build an image from the locally cloned repository.
#
# If you want to use Invidious in production, see the docker-compose.yml file provided
# in the installation documentation: https://docs.invidious.io/installation/

version: "3"
services:

  invidious-refresher:
    image: git.nadeko.net/fijxu/invidious:latest
    restart: unless-stopped
    volumes:
      - ./config/config-refresher.yml:/etc/invidious/config.yml:ro
      - ./logs:/var/log/invidious:rw
      - /var/run/postgresql/.s.PGSQL.5432:/var/run/postgresql/.s.PGSQL.5432:rw
      - /var/run/redis/redis.sock:/var/run/redis/redis.sock:rw
    environment:
      INVIDIOUS_CONFIG_FILE: /etc/invidious/config.yml

  invidious:
    image: git.nadeko.net/fijxu/invidious:latest
    restart: unless-stopped
    deploy: 
      replicas: 4
    volumes:
      - ./config/config.yml:/etc/invidious/config.yml:ro
      - ./logs:/var/log/invidious:rw
      - /var/run/postgresql/.s.PGSQL.5432:/var/run/postgresql/.s.PGSQL.5432:rw
      - /var/run/redis/redis.sock:/var/run/redis/redis.sock:rw
    environment:
      INVIDIOUS_CONFIG_FILE: /etc/invidious/config.yml

  invidious-nginx:
   image: nginx:latest
   restart: unless-stopped
   volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
   depends_on:
     - invidious
   ports:
     - "127.0.0.1:10011:3000"
