# Warning: This docker-compose file is made for development purposes.
# Using it will build an image from the locally cloned repository.
#
# If you want to use Invidious in production, see the docker-compose.yml file provided
# in the installation documentation: https://docs.invidious.io/installation/

version: "3"
services:

  invidious-refresher:
    image: git.nadeko.net/invidious/invidious:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./config/config.conf:/etc/config/invidious-refresher.conf

  invidious:
    image: git.nadeko.net/invidious/invidious:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    deploy: 
      replicas: 4
    volumes:
      - ./config/config.conf:/etc/config/config.conf

  invidious-nginx:
   image: nginx:latest
   restart: unless-stopped
   volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
   depends_on:
     - invidious
   ports:
     - "127.0.0.1:50011:3000"
